config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :peintures, only: [:new, :create, :show, :edit, :update, :destroy]

  root to: 'pages#home'
  get '/contact', to: 'pages#contact'


  mount Attachinary::Engine => "/attachinary"
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/peinture.rb
class Peinture < ApplicationRecord
  has_attachment :photo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @peintures = Peinture.all.order(created_at: :desc)
  end
end

app/controllers/peinture_controller.rb
class PeintureController < ApplicationController
  def index
    @peintures = Peinture.all
  end

  def show
    @peinture = Peinture.find(params[:id])
  end

  def create
    @peinture = Peinture.new(peinture_params)
    if @peinture.save
      redirect_to show_peinture(@peinture)
    else
      render :new
    end
  end

  def new
    @peinture = Peinture.new
  end

  def update
    @peinture = Peinture.find(params[:id])
    if @peinture.update(peinture_params)
      redirect_to show_peinture(@peinture)
    else
      render :edit
    end
  end

  def destroy
    @peinture = Peinture.find(params[:id])
    @peinture.destroy
  end

  private

  def peinture_params
    params.require(:product).permit(:titre, :description, :photo)
  end
end

app/controllers/peintures_controller.rb
class PeinturesController < ApplicationController

  def create
    @peinture = Peinture.new(peinture_params)
    if @peinture.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @peinture = Peinture.new
  end

  def edit
    @peinture = Peinture.find(params[:id])
  end

  def update
    @peinture = Peinture.find(params[:id])
    if @peinture.update(peinture_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @peinture = Peinture.find(params[:id])
    @peinture.destroy
    redirect_to root_path
  end

  private

  def peinture_params
    params.require(:peinture).permit(:titre, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peinture_helper.rb
module PeintureHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="icon" href="<%= image_path("favicon.png") %>">
  <title>Beatrice Kosowski</title>
  <meta name="description" content="Peintures & Art" />
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :defaults %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= yield %>
  <%= render 'shared/footer' %>
  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
</body>
</html>

app/views/pages/_peintures.html.erb
<div class="container" id="peintures">
  <div class="row">
    <% @peintures.each do |peinture| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path peinture.photo.path %>);">
        <div class="card-description">
          <h2><%= peinture.titre %></h2>
          <p><%= peinture.description %></p>
        </div>

        <a href="<%= cl_image_path peinture.photo.path %>" data-lightbox="image-1" data-title="<%= peinture.titre %>" class= "card-link">
        <img src="<%= cl_image_path peinture.photo.path %>" alt="" class="hidden">
        </a>

        <% if user_signed_in? %>

        <%= link_to edit_peinture_path(peinture), class: "btn btn-primary btn-xs card-edit-btn" do %>
        <i class="fa fa-wrench"></i>
        <% end %>
        <% end %>
      </div>
    </div>
    <% end %>
    <% if user_signed_in? && current_user.admin %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-color: whitesmoke;">
        <div class="card-description">
          <h2>Ajouter une peinture</h2>
        </div>
        <%= link_to "", new_peinture_path, class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container full-screen">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <h3>Contactez moi!</h3>
      <form method="POST" action="http://formspree.io/adriana.kosowski.bba@edhec.com">
        <div class="form-group">
          <input type="email" name="email" placeholder="Votre email" class="form-control margin-bottom" required>
          <input type="subject" name="subject" placeholder="Sujet" class="form-control margin-bottom">
          <textarea rows="5" name="message" placeholder="Votre message" class="form-control" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Envoyer <i class="fa fa-paper-plane" aria-hidden="true"></i></button>
      </form>
    </div>
    <div class="col-xs-12 col-sm-6">
    <div class="profile-card">
      <div class="profile-card-title">
        <h3>Beatrice Kosowski</h3>
        <h3><small>Peintre</small></h3>
      </div>
      <div class="profile-card-image">
        <%= image_tag "profile.jpg", class: "img-thumbnail" %>
      </div>
      <div class="profile-card-description">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laborum id, consequatur doloremque odio, tempore nostrum itaque iste ut libero hic veritatis, voluptates qui consequuntur deserunt. Ut error modi reiciendis maiores!</p>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.5) 50%), url(<%= image_path 'banner.jpg' %>);">
  <div class="banner-content">
    <%= image_tag "logo.png" %>
    <h1>Beatrice Kosowski</h1>
    <p>peintures</p>
    <i class="fa fa-angle-down hidden-xs" aria-hidden="true"></i>

  </div>
  <a href="#" class="back-to-top hidden-xs" style="background: #00C4C6 url(<%= image_path "up-arrow.png" %>) no-repeat center 43%;"></a>
</div>
<%= render "peintures" %>

app/views/peintures/edit.html.erb
<div class="container full-screen">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h3>Modifier <%= @peinture.titre %></h3>

      <%= simple_form_for @peinture do |f| %>
      <%= f.input :titre %>
      <%= f.input :description %>
      <%= f.input :photo, as: :attachinary %>
      <%= f.button :submit, "Modifier peinture", class: "btn btn-primary" %>
      <%= link_to "Supprimer peinture", peinture_path(@peinture), method: :delete, class: "btn btn-danger" %>
      <% end %>
    </div>
  </div>

</div>

app/views/peintures/new.html.erb
<div class="container full-screen">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2">
      <h3>Nouvelle Peinture</h3>

      <%= simple_form_for @peinture do |f| %>
      <%= f.input :titre %>
      <%= f.input :description %>
      <%= f.input :photo, as: :attachinary %>
      <%= f.button :submit, "Créer peinture", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

app/views/shared/_footer.html.erb
<div class="footer-container">
  <div class="footer-left text-center">
    <h4>Contact</h4>
    <ul class="list-inline">
      <li><%= link_to contact_path do %>
        <i class="fa fa-envelope hidden-xs" aria-hidden="true"></i> Contactez moi!
        <% end %>
      </li>
    </ul>
  </div>
  <div class="footer-middle text-center hidden-xs">
    <h4>Mon travail</h4>
    <ul>
      <li><%= link_to root_path do %>
        <i class="fa fa-paint-brush" aria-hidden="true"></i> Peintures
        <% end %>
      </li>
    </ul>
  </div>
  <div class='footer-right text-center hidden-xs'>
    <h4>Besoin d'un site?</h4>
    <ul class="list-inline">
      <li><a href="mailto:arthur.littmann@gmail.com"><i class="fa fa-code" aria-hidden="true"></i>Contactez le développeur</a></li>
    </ul>
  </div>
  <% if user_signed_in? %>
  <%= link_to "Déconnexion", destroy_user_session_path, :method => :delete, class: 'devise-footer' %>
  <% else %>
  <%= link_to "Administrateur", user_session_path, class: 'devise-footer' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">


    <!-- Text link -->
    <%= link_to "Mon travail", (root_path + "#peintures"), class: "navbar-wagon-item navbar-wagon-link hidden-xs" %>
    <%= link_to "Contact", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>
  </div>
</div>